### PR TITLE
Schedules Test Case

### PR DESCRIPTION
**Pull request by jorgeorpinel**

### CODE REVIEW

**Comment by jorgeorpinel** [comment]
@alexagranov it seems it's not possible to update a time window (merhod `SchedulesController::updateScheduleTimeWindowById()`). Even if I sent the very same values given when creating the time window (the current version only tries to update start and end times), there are validation errors related to `recursBy`. I think the main one is that `frequency` and `occurrence` should default to a valid value like it happens with `createScheduleTimeWindow()`

Other examples:

Validation errors referring to inexistent field "Interval"
```sh
# Object sent to updateScheduleTimeWindowById():
GonebusyLib\Models\UpdateScheduleTimeWindowByIdBody Object
(
    [dateRecursBy] => 
    [days] => wednesday
    [endDate] => 2017-03-22
    [endTime] => 19:00
    [frequency] => every
    [occurrence] => 
    [recursBy] => daily
    [startDate] => 2017-03-22
    [startTime] => 13:00
    [totalMinutes] => 
)

# PHPUnit failure message:
1) SchedulesTest::testUpdateScheduleTimeWindowById
GonebusyLib\Exceptions\EntitiesErrorException: 422 Unprocessable Entity - :interval must be :every when recurring :daily
```
^ Same happens when sending no `frequency` at all (which should default to 'every') and/or with `[recursBy] => weekly`

Unknown errors when sending `[occurrence] => every` to the above:
```sh
# Object sent to updateScheduleTimeWindowById():
GonebusyLib\Models\UpdateScheduleTimeWindowByIdBody Object
(
    [dateRecursBy] => 
    [days] => wednesday
    [endDate] => 2017-03-22
    [endTime] => 19:00
    [frequency] => 
    [occurrence] => every
    [recursBy] => daily
    [startDate] => 2017-03-22
    [startTime] => 13:00
    [totalMinutes] => 
)

# PHPUnit failure message:
1) SchedulesTest::testUpdateScheduleTimeWindowById
GonebusyLib\APIException: Unexpected error
```
^ With or without `frequency`

Unknown errors aren't helpful and also occur under other circumstances such as when sending no frequency or occurrence, and `[recursBy] => monthly`.

Among others... I just can't find a valid combination of values so this method doesn't return an exception so, stuck :T

**Comment by alexagranov** [comment]
hi @jorgeorpinel -

Let's start simple with just the base required params as per [Quick Start - Step 3](https://gonebusy.github.io/api#/quick_start#step_3) 

```
{
  "start_date": "2016-11-01",
  "end_date": "2017-01-31",
  "start_time": "4pm",
  "end_time": "11pm",
  "recurs_by": "weekly",
  "days": "monday, wednesday, friday"
}
```

These params can work for POST /schedules/new, POST /schedules/:id/time_windows/new, and PUT /schedules/:id/time_windows/:tw_id but you'll need to modify something like "end_date" for the PUT.

**Comment by jorgeorpinel** [comment]
Hi @alexagranov trying to get back on this now.

Regarding your previous message, the SDK requires all params.  One can send `NULL` for any empty values but I don't remember right now what exact REST call it does internally -- I think it sends an empty value instead of omitting the params though. Anyway, sending only those values to the SDK wasn't working for me.  I'll give it another shot.

**Comment by jorgeorpinel** [comment]
Hi @alexagranov me again on this. I tried again and unfortunately again, the SDK doesn't have a way to specify the exact REST requestbody to send like in the Quick Start - Step 3 you refer to. You must always send all the params to `GonebusyLib\Controllers\SchedulesController::updateScheduleTimeWindowById()` -- where the one problem with this test exists.

The API returns the same messages I described above about an ":interval" or an "Unknown error" with whichever combination of params I send to that method. For example, the present code tries to go from this existing time window:

```
GonebusyLib\Models\EntitiesTimeWindowResponse Object
(
    [dateRecursBy] => 
    [days] => Array
        (
            [0] => sunday
            [1] => monday
            [2] => tuesday
            [3] => wednesday
            [4] => thursday
            [5] => friday
            [6] => saturday
        )

    [endDate] => 2017-04-03
    [endTime] => 18:00
    [frequency] => every
    [id] => 6094243291
    [negation] => 
    [occurrence] => every
    [recursBy] => daily
    [startDate] => 2017-04-03
    [startTime] => 12:00
    [totalMinutes] => 360
)
```

to the one described by this new time window body:

```
GonebusyLib\Models\UpdateScheduleTimeWindowByIdBody Object
(
    [dateRecursBy] => 
    [days] => sunday
    [endDate] => 2017-04-02
    [endTime] => 19:00
    [frequency] => 
    [occurrence] => 
    [recursBy] => once
    [startDate] => 2017-04-02
    [startTime] => 13:00
    [totalMinutes] => 
)
```

bu calling the time window update method. The following body is sent via HTTP (REST) by that method:
`{"date_recurs_by":null,"days":"sunday","end_date":"2017-04-02","end_time":"19:00","frequency":null,"occurrence":null,"recurs_by":"once","start_date":"2017-04-02","start_time":"13:00","total_minutes":null}
`

and this error message is returned with the API's 422 response: "422 Unprocessable Entity - Interval must be :every when recurring :once"

"Interval" isn't a known parameter, and both `frequency` and `occurrence`  are supposed to default to :every when sending null (see [time window update API doc.](https://gonebusy.github.io/api#/schedules#put_schedules_id_time_windows_id)). If I send `every` to `frequency`,  the API complaints that "Frequency must be :single when recurring :once" and the same error message is returned **even when I send `single`** to `frequency`.

In conclusion, when updating time windows, the API validation seems to result in a logical fallacy (where there's no right answer).

I hope I'm not missing anything but I really tried for some time with different parameters, would you please check? In `SchedulesTest.p` you may modify the parameters in lines 125-137 and uncomment my `echo` and `print_r`s in method `testUpdateScheduleTimeWindowById` to see the before and after time window (in SDK PHP format).
You would additionally need, in `src/Controllers/SchedulesController.php` to `print_r(Request\Body::Json($updateScheduleTimeWindowByIdBody));` before line 549 to see the actual REST request body sent to the API.

Sorry for the long message!

p.s. I could tell the test to expect that 422 error in order to have a passing test if what you'd like is to be able to close this PR. I'll move onto Bookings for now.

**Comment by jorgeorpinel** [comment]
Another p.s. even if I use the exact same body sent to create the time window we're trying to update (copy lines 112-121 into 125-137)  --or if I just try to change a simple value such as `end_date`-- the SDK throws: "GonebusyLib\Exceptions\EntitiesErrorException: end_date is invalid, recurs_by does not have a valid value, frequency does not have a valid value, date_recurs_by does not have a valid value"

**Comment by alexagranov** [comment]
@jorgeorpinel I appreciate the extensive and novel approach to bug reporting (pun intended ;-) but I'm going to just jump in on this branch and see for myself what's going on.

So far, I see 2 failing specs in this PR: 

```

**Comment by alexagranov** [comment]
Problem 1) - testDeleteScheduleById

In this test, you are attempting to verify that returned version of Schedule after DELETE can be marshaled into a CreateScheduleBody via https://github.com/gonebusy/gonebusy-php-client/pull/23/files#diff-6a9f8e89658e18b9d2726563f17ce32dR307.

The problem with this approach is that after a DELETE of a Schedule there are no longer any TWs associated with the Schedule so the marshaling code here that attempts to index into TWs returned fails: https://github.com/gonebusy/gonebusy-php-client/pull/23/files#diff-6a9f8e89658e18b9d2726563f17ce32dR307

This a sample response from DELETE /schedules/:id - 

```js
{
  "schedule": {
    "time_windows": [],
    "id": 1425690383,
    "owner_id": 8552697701,
    "resource_id": 6815786092,
    "service_id": 9268520168
  }
}
```

My suggestion is to simply assert the returned id, resource_id, and service_id and not worry about constructing a CreateScheduleBody from returned response.

**Comment by alexagranov** [comment]
Problem 2) - testUpdateScheduleTimeWindowById

I can confirm there appears to be a bug updating an existing TW given all the various inputs you're trying to change at the same time.  Looks like I need to bulk up my specs for that endpoint as I don't have quite the permutations that you have here.

That said, to get this PR moving ahead, all you need to do to get this test to pass is only change the `update` TW body to something like this:

```
            case 'update':
                return new UpdateScheduleTimeWindowByIdBody(
                    NULL, // date_recurs_by
                    NULL, // other days
                    NULL, // another end_date
                    '19:00', // antoher end_time
                    NULL, // frequency should default to 'every'
                    NULL, // occurrence should default to 'every'
                    NULL, // recurs_by
                    NULL, // start_date
                    '13:00', // anther start_time
                    NULL // total_minutes
                );
```

And then remove this assertion https://github.com/gonebusy/gonebusy-php-client/pull/23/files#diff-6a9f8e89658e18b9d2726563f17ce32dR391 as it not valid to expect the returned Schedule to match the partially constructed request Body we passed.

I'll update you when I've corrected the underlying update issues and have issued another release of the API.

Thanks for debugging! 💥

**Comment by jorgeorpinel** [comment]
@alexagranov on Problem 1) - testDeleteScheduleById : 

I hadn't even noticed that. My machine doesn't complain but it is indeed happening (as shown also in the [previous build](https://travis-ci.org/gonebusy/gonebusy-php-client/jobs/217887155)). It seems it's a strict kind of error not reported by default on php56. I updated my system's php.ini and now I see it.

Anyway, your suggestion is spot on (actually better since I was asserting only on the `serviceId` property already) and I did that to fix it (see [current build](https://travis-ci.org/gonebusy/gonebusy-php-client/jobs/222309602)), in the above commit.

**Comment by jorgeorpinel** [comment]
@alexagranov on Problem 2) - testUpdateScheduleTimeWindowById:

> remove [this assertion](https://github.com/gonebusy/gonebusy-php-client/pull/23/files#diff-6a9f8e89658e18b9d2726563f17ce32dR391) as it not valid to expect the returned Schedule to match the partially constructed request Body we passed.

Makes sense.

> You do still have to remove the assertion... I'll leave it up to you what else you want to assert at that point

In the above commit I just asserted the response class type, as well as start/end dates and times.

p.s. The SDK is returning an empty frequency instead of the value "single" which I sent into `updateScheduleTimeWindowById()`. Is that a bug? Otherwise I could leave the assert on the full schedule bodies!

**Comment by alexagranov** [comment]
Nice work!

I can't recreate the null `frequency` in response for testUpdateScheduleTimeWindowById but I'll make a note to investigate what's up in the test code.

Merging for now as this is passing CI.

**Comment by jorgeorpinel** [comment]
Hey @alexagranov yeah actually I tried again and I'm getting the same `frequency` back. It was my bad when re-creating the request body in bodyFromResponse() (See https://github.com/jorgeorpinel/gonebusy-php-client/commit/1b8abb4fd95cfde13bd52ae10931aefaa07a441e#diff-6a9f8e89658e18b9d2726563f17ce32dR185). I'll open a new PR in case you prefer that version.

**Pull request merged**
